### ISSUE TITLE
Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.

### ISSUE THREAD

**Issue by zeteticl** [igrigorik/ga-beacon#74] opened 2020-08-09 03:26 UTC
hope fix

**Comment by shuuji3** [comment] 2020-08-09 03:55
This issue seems to have been fixed by #69. :slightly_smiling_face:

**Comment by aravindvnair99** [comment] 2020-08-10 20:36
Duplicate of #73 @zeteticl

**Closed** 2020-09-13 04:26 UTC
